//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""button"",
            ""id"": ""b021c531-f0d9-433d-a36c-e7be77256ebe"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""4de0845b-0716-4db8-94f1-fb1ce3d214a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a65ae744-a6e8-48e4-a116-f218bdbe5e50"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // button
        m_button = asset.FindActionMap("button", throwIfNotFound: true);
        m_button_Tap = m_button.FindAction("Tap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // button
    private readonly InputActionMap m_button;
    private List<IButtonActions> m_ButtonActionsCallbackInterfaces = new List<IButtonActions>();
    private readonly InputAction m_button_Tap;
    public struct ButtonActions
    {
        private @NewControls m_Wrapper;
        public ButtonActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_button_Tap;
        public InputActionMap Get() { return m_Wrapper.m_button; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ButtonActions set) { return set.Get(); }
        public void AddCallbacks(IButtonActions instance)
        {
            if (instance == null || m_Wrapper.m_ButtonActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ButtonActionsCallbackInterfaces.Add(instance);
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
        }

        private void UnregisterCallbacks(IButtonActions instance)
        {
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
        }

        public void RemoveCallbacks(IButtonActions instance)
        {
            if (m_Wrapper.m_ButtonActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IButtonActions instance)
        {
            foreach (var item in m_Wrapper.m_ButtonActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ButtonActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ButtonActions @button => new ButtonActions(this);
    public interface IButtonActions
    {
        void OnTap(InputAction.CallbackContext context);
    }
}
